print("Digite seu nome:")
nome = input()
print("Bem-vindo, ", nome)
idade = int(input(f"Informe a sua idade {nome} : "))
semestre1 = float(input("Informe a nota do 1º Semestre :"))
print(f"Seu nome é {nome}, sua idade é {idade} e sua nota do semestre passado foi {semestre1}")